DROP TABLE IF EXISTS Answer;
DROP TABLE IF EXISTS Response;
DROP TABLE IF EXISTS RoundResponse;
DROP TABLE IF EXISTS QuizMember;
DROP TABLE IF EXISTS QuestionInRound;
DROP TABLE IF EXISTS Round;
DROP TABLE IF EXISTS QuizSession;
DROP TABLE IF EXISTS Quiz;
DROP TABLE IF EXISTS Question;
DROP TABLE IF EXISTS UserSession;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Topic;

CREATE TABLE Topic (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TopicName TEXT
);

CREATE TABLE User (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Username TEXT UNIQUE,
  Name TEXT,
  Password TEXT,
  Email TEXT
);

CREATE TABLE UserSession (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Token TEXT,
  UserID TEXT,
  LastUsed INTEGER,
  FOREIGN KEY (UserID) REFERENCES User(ID)
);

CREATE TABLE Question (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  QuestionText TEXT,
  AuthorID INTEGER,
  TopicID INTEGER,
  MultipleChoice BOOLEAN,
  Difficulty TEXT,
  FOREIGN KEY (AuthorID) REFERENCES User(ID)
  FOREIGN KEY (TopicID) REFERENCES Topic(ID)
);

CREATE TABLE Answer (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  QuestionID INTEGER,
  AnswerText TEXT,
  Correct BOOLEAN,
  FOREIGN KEY (QuestionID) REFERENCES Question(ID)
);

CREATE TABLE Quiz (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Generator INTEGER,
  NumQuestions INTEGER,
  Difficulty INTEGER,
  FOREIGN KEY (Generator) REFERENCES User(ID)
);

CREATE TABLE QuizSession (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Creator INTEGER,
  QuizID INTEGER,
  SessionCode TEXT,
  StartTime INTEGER,
  FOREIGN KEY (Creator) REFERENCES User(ID),
  FOREIGN KEY (QuizID) REFERENCES Quiz(ID)
);

CREATE TABLE Round (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TopicID INTEGER,
  QuizID INTEGER,
  StartDT INTEGER,
  FOREIGN KEY (QuizID) REFERENCES Quiz(ID)
  FOREIGN KEY (TopicID) REFERENCES Topic(ID)
);

CREATE TABLE QuestionInRound (
  QuestionID INTEGER,
  RoundID INTEGER,
  FOREIGN KEY (QuestionID) REFERENCES Question(ID),
  FOREIGN KEY (RoundID) REFERENCES Round(ID)
);

CREATE TABLE QuizMember (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  UserID INTEGER,
  SessionID INTEGER,
  Score INTEGER,
  FOREIGN KEY (UserID) REFERENCES User(ID),
  FOREIGN KEY (SessionID) REFERENCES QuizSession(ID)
);

CREATE TABLE RoundResponse (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  QuizMemberID INTEGER,
  RoundID INTEGER,
  EndDT INTEGER,
  Score INTEGER,
  FOREIGN KEY (RoundID) REFERENCES Round(ID),
  FOREIGN KEY (QuizMemberID) REFERENCES QuizMember(ID)
);

CREATE TABLE Response (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Answer TEXT,
  RoundResponseID INTEGER,
  QuestionID INTEGER,
  FOREIGN KEY (QuestionID) REFERENCES Question(ID),
  FOREIGN KEY (RoundResponseID) REFERENCES RoundResponse(ID)
);

